#!/usr/bin/env python3
"""Turn the frames in figma/ (PNG exports) into graphics_test/graphics.h.

Each frame is scaled down to fit inside 160x80 without distortion (high-quality Lanczos),
centred on black, converted to RGB565, and written as a C array. Needs ffmpeg.

    python3 make_graphics.py
"""
import glob, os, struct, subprocess

os.makedirs("fit", exist_ok=True)
frames = sorted(glob.glob("figma/*.png"))
arrays = []
for f in frames:
    name = os.path.splitext(os.path.basename(f))[0]
    png, raw = f"fit/{name}.png", f"fit/{name}.raw"
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", f, "-vf",
                    "scale=w=160:h=80:force_original_aspect_ratio=decrease:flags=lanczos,"
                    "pad=160:80:(ow-iw)/2:(oh-ih)/2:color=black", png], check=True)
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", png,
                    "-f", "rawvideo", "-pix_fmt", "rgb565le", raw], check=True)
    data = open(raw, "rb").read()
    px = struct.unpack("<%dH" % (len(data) // 2), data)
    rows = ["    " + ", ".join("0x%04x" % p for p in px[i:i + 16]) + "," for i in range(0, len(px), 16)]
    arrays.append(f"  {{  // {name}\n" + "\n".join(rows) + "\n  },")

header = [
    "// Generated by make_graphics.py from the frames in figma/ (fitted into 160x80, RGB565).",
    "// Not in git: the frames are design work. Regenerate rather than editing by hand.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    f"static const int GRAPHIC_W = 160, GRAPHIC_H = 80, GRAPHIC_COUNT = {len(frames)};",
    "",
    f"static const uint16_t GRAPHICS[{len(frames)}][160 * 80] = {{",
    *arrays,
    "};",
]
open("graphics_test/graphics.h", "w").write("\n".join(header) + "\n")
print(f"{len(frames)} frames -> graphics_test/graphics.h")
