#!/usr/bin/env python3
"""Turn the frames in figma/ (PNG exports) into graphics_test/graphics.h.

Figma renders each frame on its grey canvas, so the area outside the frame's rounded corners
comes out grey. That grey (and the anti-aliased edge between it and the frame's black
background) is flood-filled to black from the four corners; the fill stops at the frame's
black background, so grey artwork inside the frame is left alone. Each frame is then scaled
down to fit inside 160x80 without distortion (Lanczos), centred on black, converted to
RGB565 and written as a C array. Needs Pillow.

    python3 make_graphics.py
"""
import glob, os
from collections import deque
from PIL import Image

W, H = 160, 80


def blacken_corners(img):
    """Flood-fill the canvas showing through the rounded corners with black."""
    px = img.load()
    w, h = img.size
    seen = set()
    queue = deque([(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)])

    def canvas(c):
        r, g, b = c[:3]
        # Neutral and not (nearly) black: the canvas grey or its blend into the black frame.
        return max(r, g, b) > 24 and max(r, g, b) - min(r, g, b) < 24

    while queue:
        x, y = queue.popleft()
        if (x, y) in seen or not (0 <= x < w and 0 <= y < h) or not canvas(px[x, y]):
            continue
        seen.add((x, y))
        px[x, y] = (0, 0, 0)
        queue.extend([(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)])
    return img


def fit(img):
    """Scale to fit inside W x H without distortion, centred on black."""
    scale = min(W / img.width, H / img.height)
    size = (round(img.width * scale), round(img.height * scale))
    small = img.resize(size, Image.LANCZOS)
    out = Image.new("RGB", (W, H), (0, 0, 0))
    out.paste(small, ((W - size[0]) // 2, (H - size[1]) // 2))
    return out


def rgb565(img):
    data = img.tobytes()  # RGB, 3 bytes a pixel
    return [((data[i] >> 3) << 11) | ((data[i + 1] >> 2) << 5) | (data[i + 2] >> 3)
            for i in range(0, len(data), 3)]


os.makedirs("fit", exist_ok=True)
frames = sorted(glob.glob("figma/*.png"))
arrays = []
for f in frames:
    name = os.path.splitext(os.path.basename(f))[0]
    img = fit(blacken_corners(Image.open(f).convert("RGB")))
    img.save(f"fit/{name}.png")
    px = rgb565(img)
    rows = ["    " + ", ".join("0x%04x" % p for p in px[i:i + 16]) + "," for i in range(0, len(px), 16)]
    arrays.append(f"  {{  // {name}\n" + "\n".join(rows) + "\n  },")

header = [
    "// Generated by make_graphics.py from the frames in figma/ (fitted into 160x80, RGB565).",
    "// Not in git: the frames are design work. Regenerate rather than editing by hand.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    f"static const int GRAPHIC_W = {W}, GRAPHIC_H = {H}, GRAPHIC_COUNT = {len(frames)};",
    "",
    f"static const uint16_t GRAPHICS[{len(frames)}][{W} * {H}] = {{",
    *arrays,
    "};",
]
open("graphics_test/graphics.h", "w").write("\n".join(header) + "\n")
print(f"{len(frames)} frames -> graphics_test/graphics.h")
